using System.Text;

namespace EnterpriseAutomationFramework.Services.Reporting;

/// <summary>
/// HTML 模板提供器
/// </summary>
public class HtmlTemplateProvider
{
    /// <summary>
    /// 获取主模板
    /// </summary>
    /// <returns>主模板HTML</returns>
    public async Task<string> GetMainTemplateAsync()
    {
        return await Task.FromResult(GetMainTemplate());
    }

    /// <summary>
    /// 获取样式表
    /// </summary>
    /// <returns>CSS样式表</returns>
    public async Task<string> GetStylesheetAsync()
    {
        return await Task.FromResult(GetStylesheet());
    }

    /// <summary>
    /// 获取JavaScript脚本
    /// </summary>
    /// <returns>JavaScript脚本</returns>
    public async Task<string> GetJavaScriptAsync()
    {
        return await Task.FromResult(GetJavaScript());
    }

    /// <summary>
    /// 获取主模板
    /// </summary>
    /// <returns>主模板HTML</returns>
    private static string GetMainTemplate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang='zh-CN'>");
        sb.AppendLine("<head>");
        sb.AppendLine("    <meta charset='UTF-8'>");
        sb.AppendLine("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        sb.AppendLine("    <title>{{REPORT_TITLE}} - 测试报告</title>");
        sb.AppendLine("    <link rel='stylesheet' href='assets/report.css'>");
        sb.AppendLine("    <script src='https://cdn.jsdelivr.net/npm/chart.js'></script>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("    <div class='container'>");
        sb.AppendLine("        <!-- 报告头部 -->");
        sb.AppendLine("        <header class='report-header'>");
        sb.AppendLine("            <div class='header-content'>");
        sb.AppendLine("                <h1>{{REPORT_TITLE}}</h1>");
        sb.AppendLine("                <div class='report-meta'>");
        sb.AppendLine("                    <div class='meta-item'>");
        sb.AppendLine("                        <span class='meta-label'>生成时间:</span>");
        sb.AppendLine("                        <span class='meta-value'>{{REPORT_GENERATED_AT}}</span>");
        sb.AppendLine("                    </div>");
        sb.AppendLine("                    <div class='meta-item'>");
        sb.AppendLine("                        <span class='meta-label'>测试环境:</span>");
        sb.AppendLine("                        <span class='meta-value'>{{ENVIRONMENT}}</span>");
        sb.AppendLine("                    </div>");
        sb.AppendLine("                    <div class='meta-item'>");
        sb.AppendLine("                        <span class='meta-label'>执行时间:</span>");
        sb.AppendLine("                        <span class='meta-value'>{{TEST_START_TIME}} - {{TEST_END_TIME}}</span>");
        sb.AppendLine("                    </div>");
        sb.AppendLine("                    <div class='meta-item'>");
        sb.AppendLine("                        <span class='meta-label'>总耗时:</span>");
        sb.AppendLine("                        <span class='meta-value'>{{TOTAL_DURATION}}</span>");
        sb.AppendLine("                    </div>");
        sb.AppendLine("                </div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("        </header>");
        sb.AppendLine();
        sb.AppendLine("        <!-- 导航菜单 -->");
        sb.AppendLine("        <nav class='report-nav'>");
        sb.AppendLine("            <ul class='nav-list'>");
        sb.AppendLine("                <li><a href='#summary' class='nav-link active'>摘要</a></li>");
        sb.AppendLine("                <li><a href='#charts' class='nav-link'>图表</a></li>");
        sb.AppendLine("                <li><a href='#results' class='nav-link'>测试结果</a></li>");
        sb.AppendLine("                <li><a href='#failures' class='nav-link'>失败详情</a></li>");
        sb.AppendLine("                <li><a href='#screenshots' class='nav-link'>截图</a></li>");
        sb.AppendLine("                <li><a href='#system' class='nav-link'>系统信息</a></li>");
        sb.AppendLine("            </ul>");
        sb.AppendLine("        </nav>");
        sb.AppendLine();
        sb.AppendLine("        <!-- 主要内容 -->");
        sb.AppendLine("        <main class='report-content'>");
        sb.AppendLine("            <!-- 摘要部分 -->");
        sb.AppendLine("            <section id='summary' class='report-section'>");
        sb.AppendLine("                <h2>测试摘要</h2>");
        sb.AppendLine("                {{SUMMARY_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine();
        sb.AppendLine("            <!-- 图表部分 -->");
        sb.AppendLine("            <section id='charts' class='report-section'>");
        sb.AppendLine("                <h2>统计图表</h2>");
        sb.AppendLine("                {{CHARTS_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine();
        sb.AppendLine("            <!-- 测试结果部分 -->");
        sb.AppendLine("            <section id='results' class='report-section'>");
        sb.AppendLine("                {{RESULTS_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine();
        sb.AppendLine("            <!-- 失败测试部分 -->");
        sb.AppendLine("            <section id='failures' class='report-section'>");
        sb.AppendLine("                {{FAILED_TESTS_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine();
        sb.AppendLine("            <!-- 截图部分 -->");
        sb.AppendLine("            <section id='screenshots' class='report-section'>");
        sb.AppendLine("                {{SCREENSHOTS_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine();
        sb.AppendLine("            <!-- 系统信息部分 -->");
        sb.AppendLine("            <section id='system' class='report-section'>");
        sb.AppendLine("                {{SYSTEM_INFO_SECTION}}");
        sb.AppendLine("                {{CONFIGURATION_SECTION}}");
        sb.AppendLine("                {{METADATA_SECTION}}");
        sb.AppendLine("            </section>");
        sb.AppendLine("        </main>");
        sb.AppendLine();
        sb.AppendLine("        <!-- 页脚 -->");
        sb.AppendLine("        <footer class='report-footer'>");
        sb.AppendLine("            <p>&copy; 2024 Enterprise Automation Framework. Generated at {{REPORT_GENERATED_AT}}</p>");
        sb.AppendLine("        </footer>");
        sb.AppendLine("    </div>");
        sb.AppendLine();
        sb.AppendLine("    <!-- 模态框 -->");
        sb.AppendLine("    <div id='screenshotModal' class='modal'>");
        sb.AppendLine("        <div class='modal-content'>");
        sb.AppendLine("            <span class='close'>&times;</span>");
        sb.AppendLine("            <img id='modalImage' src='' alt='Screenshot' />");
        sb.AppendLine("        </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine();
        sb.AppendLine("    <div id='testDetailsModal' class='modal'>");
        sb.AppendLine("        <div class='modal-content'>");
        sb.AppendLine("            <span class='close'>&times;</span>");
        sb.AppendLine("            <div id='testDetailsContent'></div>");
        sb.AppendLine("        </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine();
        sb.AppendLine("    <script src='assets/report.js'></script>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        
        return sb.ToString();
    }

    /// <summary>
    /// 获取样式表
    /// </summary>
    /// <returns>CSS样式表</returns>
    private static string GetStylesheet()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* 基础样式 */");
        sb.AppendLine("* {");
        sb.AppendLine("    margin: 0;");
        sb.AppendLine("    padding: 0;");
        sb.AppendLine("    box-sizing: border-box;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("body {");
        sb.AppendLine("    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        sb.AppendLine("    line-height: 1.6;");
        sb.AppendLine("    color: #333;");
        sb.AppendLine("    background-color: #f5f5f5;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".container {");
        sb.AppendLine("    max-width: 1200px;");
        sb.AppendLine("    margin: 0 auto;");
        sb.AppendLine("    background-color: white;");
        sb.AppendLine("    box-shadow: 0 0 20px rgba(0,0,0,0.1);");
        sb.AppendLine("    min-height: 100vh;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 报告头部 */");
        sb.AppendLine(".report-header {");
        sb.AppendLine("    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
        sb.AppendLine("    color: white;");
        sb.AppendLine("    padding: 2rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".header-content h1 {");
        sb.AppendLine("    font-size: 2.5rem;");
        sb.AppendLine("    margin-bottom: 1rem;");
        sb.AppendLine("    text-shadow: 2px 2px 4px rgba(0,0,0,0.3);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".report-meta {");
        sb.AppendLine("    display: grid;");
        sb.AppendLine("    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));");
        sb.AppendLine("    gap: 1rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".meta-item {");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".meta-label {");
        sb.AppendLine("    font-size: 0.9rem;");
        sb.AppendLine("    opacity: 0.8;");
        sb.AppendLine("    margin-bottom: 0.25rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".meta-value {");
        sb.AppendLine("    font-size: 1.1rem;");
        sb.AppendLine("    font-weight: 600;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 导航菜单 */");
        sb.AppendLine(".report-nav {");
        sb.AppendLine("    background-color: #2c3e50;");
        sb.AppendLine("    padding: 0;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".nav-list {");
        sb.AppendLine("    list-style: none;");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-wrap: wrap;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".nav-list li {");
        sb.AppendLine("    flex: 1;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".nav-link {");
        sb.AppendLine("    display: block;");
        sb.AppendLine("    padding: 1rem;");
        sb.AppendLine("    color: white;");
        sb.AppendLine("    text-decoration: none;");
        sb.AppendLine("    text-align: center;");
        sb.AppendLine("    transition: background-color 0.3s;");
        sb.AppendLine("    border-right: 1px solid #34495e;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".nav-link:hover,");
        sb.AppendLine(".nav-link.active {");
        sb.AppendLine("    background-color: #3498db;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 主要内容 */");
        sb.AppendLine(".report-content {");
        sb.AppendLine("    padding: 2rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".report-section {");
        sb.AppendLine("    margin-bottom: 3rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".report-section h2 {");
        sb.AppendLine("    color: #2c3e50;");
        sb.AppendLine("    border-bottom: 3px solid #3498db;");
        sb.AppendLine("    padding-bottom: 0.5rem;");
        sb.AppendLine("    margin-bottom: 1.5rem;");
        sb.AppendLine("    font-size: 1.8rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 摘要卡片 */");
        sb.AppendLine(".summary-cards {");
        sb.AppendLine("    display: grid;");
        sb.AppendLine("    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));");
        sb.AppendLine("    gap: 1.5rem;");
        sb.AppendLine("    margin-bottom: 2rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".summary-card {");
        sb.AppendLine("    background: white;");
        sb.AppendLine("    border-radius: 10px;");
        sb.AppendLine("    padding: 1.5rem;");
        sb.AppendLine("    box-shadow: 0 4px 6px rgba(0,0,0,0.1);");
        sb.AppendLine("    border-left: 5px solid;");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    align-items: center;");
        sb.AppendLine("    gap: 1rem;");
        sb.AppendLine("    transition: transform 0.3s, box-shadow 0.3s;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".summary-card:hover {");
        sb.AppendLine("    transform: translateY(-2px);");
        sb.AppendLine("    box-shadow: 0 6px 12px rgba(0,0,0,0.15);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".summary-card.total { border-left-color: #3498db; }");
        sb.AppendLine(".summary-card.passed { border-left-color: #28a745; }");
        sb.AppendLine(".summary-card.failed { border-left-color: #dc3545; }");
        sb.AppendLine(".summary-card.skipped { border-left-color: #ffc107; }");
        sb.AppendLine(".summary-card.duration { border-left-color: #17a2b8; }");
        sb.AppendLine();
        sb.AppendLine(".card-icon {");
        sb.AppendLine("    font-size: 2rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".card-content {");
        sb.AppendLine("    flex: 1;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".card-number {");
        sb.AppendLine("    font-size: 2rem;");
        sb.AppendLine("    font-weight: bold;");
        sb.AppendLine("    line-height: 1;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".card-label {");
        sb.AppendLine("    font-size: 0.9rem;");
        sb.AppendLine("    color: #666;");
        sb.AppendLine("    margin-top: 0.25rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".card-percentage {");
        sb.AppendLine("    font-size: 0.8rem;");
        sb.AppendLine("    color: #888;");
        sb.AppendLine("    margin-top: 0.25rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 图表容器 */");
        sb.AppendLine(".charts-container {");
        sb.AppendLine("    display: grid;");
        sb.AppendLine("    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));");
        sb.AppendLine("    gap: 2rem;");
        sb.AppendLine("    margin-bottom: 2rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".chart-container {");
        sb.AppendLine("    background: white;");
        sb.AppendLine("    border-radius: 10px;");
        sb.AppendLine("    padding: 1.5rem;");
        sb.AppendLine("    box-shadow: 0 4px 6px rgba(0,0,0,0.1);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".chart-container h3 {");
        sb.AppendLine("    text-align: center;");
        sb.AppendLine("    margin-bottom: 1rem;");
        sb.AppendLine("    color: #2c3e50;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 模态框 */");
        sb.AppendLine(".modal {");
        sb.AppendLine("    display: none;");
        sb.AppendLine("    position: fixed;");
        sb.AppendLine("    z-index: 1000;");
        sb.AppendLine("    left: 0;");
        sb.AppendLine("    top: 0;");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: 100%;");
        sb.AppendLine("    background-color: rgba(0,0,0,0.8);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".modal-content {");
        sb.AppendLine("    position: relative;");
        sb.AppendLine("    margin: 5% auto;");
        sb.AppendLine("    padding: 20px;");
        sb.AppendLine("    width: 90%;");
        sb.AppendLine("    max-width: 800px;");
        sb.AppendLine("    background: white;");
        sb.AppendLine("    border-radius: 10px;");
        sb.AppendLine("    max-height: 80vh;");
        sb.AppendLine("    overflow-y: auto;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".close {");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    right: 15px;");
        sb.AppendLine("    top: 15px;");
        sb.AppendLine("    font-size: 28px;");
        sb.AppendLine("    font-weight: bold;");
        sb.AppendLine("    cursor: pointer;");
        sb.AppendLine("    color: #aaa;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".close:hover {");
        sb.AppendLine("    color: #000;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#modalImage {");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: auto;");
        sb.AppendLine("    border-radius: 5px;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 测试结果表格 */");
        sb.AppendLine(".results-table-container {");
        sb.AppendLine("    overflow-x: auto;");
        sb.AppendLine("    margin-top: 1rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".results-table {");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    border-collapse: collapse;");
        sb.AppendLine("    background: white;");
        sb.AppendLine("    border-radius: 8px;");
        sb.AppendLine("    overflow: hidden;");
        sb.AppendLine("    box-shadow: 0 2px 4px rgba(0,0,0,0.1);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".results-table th,");
        sb.AppendLine(".results-table td {");
        sb.AppendLine("    padding: 12px;");
        sb.AppendLine("    text-align: left;");
        sb.AppendLine("    border-bottom: 1px solid #eee;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".results-table th {");
        sb.AppendLine("    background-color: #f8f9fa;");
        sb.AppendLine("    font-weight: 600;");
        sb.AppendLine("    color: #2c3e50;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".result-row.hidden {");
        sb.AppendLine("    display: none;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 过滤器按钮 */");
        sb.AppendLine(".filters {");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    justify-content: center;");
        sb.AppendLine("    gap: 1rem;");
        sb.AppendLine("    margin-bottom: 1rem;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".filter-btn {");
        sb.AppendLine("    padding: 0.5rem 1rem;");
        sb.AppendLine("    border: 2px solid #3498db;");
        sb.AppendLine("    background: white;");
        sb.AppendLine("    color: #3498db;");
        sb.AppendLine("    border-radius: 25px;");
        sb.AppendLine("    cursor: pointer;");
        sb.AppendLine("    transition: all 0.3s;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(".filter-btn.active,");
        sb.AppendLine(".filter-btn:hover {");
        sb.AppendLine("    background: #3498db;");
        sb.AppendLine("    color: white;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 响应式设计 */");
        sb.AppendLine("@media (max-width: 768px) {");
        sb.AppendLine("    .container {");
        sb.AppendLine("        margin: 0;");
        sb.AppendLine("        box-shadow: none;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .report-content {");
        sb.AppendLine("        padding: 1rem;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .summary-cards {");
        sb.AppendLine("        grid-template-columns: 1fr;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .charts-container {");
        sb.AppendLine("        grid-template-columns: 1fr;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .nav-list {");
        sb.AppendLine("        flex-direction: column;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/* 打印样式 */");
        sb.AppendLine("@media print {");
        sb.AppendLine("    .report-nav,");
        sb.AppendLine("    .filters,");
        sb.AppendLine("    .btn-details {");
        sb.AppendLine("        display: none !important;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .container {");
        sb.AppendLine("        box-shadow: none;");
        sb.AppendLine("        max-width: none;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .report-content {");
        sb.AppendLine("        padding: 0;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    .chart-container {");
        sb.AppendLine("        break-inside: avoid;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    /// <summary>
    /// 获取JavaScript脚本
    /// </summary>
    /// <returns>JavaScript脚本</returns>
    private static string GetJavaScript()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// 页面加载完成后初始化");
        sb.AppendLine("document.addEventListener('DOMContentLoaded', function() {");
        sb.AppendLine("    initializeNavigation();");
        sb.AppendLine("    initializeFilters();");
        sb.AppendLine("    initializeModals();");
        sb.AppendLine("    initializeScrollSpy();");
        sb.AppendLine("});");
        sb.AppendLine();
        sb.AppendLine("// 初始化导航");
        sb.AppendLine("function initializeNavigation() {");
        sb.AppendLine("    const navLinks = document.querySelectorAll('.nav-link');");
        sb.AppendLine("    ");
        sb.AppendLine("    navLinks.forEach(link => {");
        sb.AppendLine("        link.addEventListener('click', function(e) {");
        sb.AppendLine("            e.preventDefault();");
        sb.AppendLine("            ");
        sb.AppendLine("            // 移除所有活动状态");
        sb.AppendLine("            navLinks.forEach(l => l.classList.remove('active'));");
        sb.AppendLine("            ");
        sb.AppendLine("            // 添加当前活动状态");
        sb.AppendLine("            this.classList.add('active');");
        sb.AppendLine("            ");
        sb.AppendLine("            // 滚动到目标部分");
        sb.AppendLine("            const targetId = this.getAttribute('href').substring(1);");
        sb.AppendLine("            const targetElement = document.getElementById(targetId);");
        sb.AppendLine("            ");
        sb.AppendLine("            if (targetElement) {");
        sb.AppendLine("                targetElement.scrollIntoView({");
        sb.AppendLine("                    behavior: 'smooth',");
        sb.AppendLine("                    block: 'start'");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 初始化过滤器");
        sb.AppendLine("function initializeFilters() {");
        sb.AppendLine("    const filterBtns = document.querySelectorAll('.filter-btn');");
        sb.AppendLine("    const resultRows = document.querySelectorAll('.result-row');");
        sb.AppendLine("    ");
        sb.AppendLine("    filterBtns.forEach(btn => {");
        sb.AppendLine("        btn.addEventListener('click', function() {");
        sb.AppendLine("            // 移除所有活动状态");
        sb.AppendLine("            filterBtns.forEach(b => b.classList.remove('active'));");
        sb.AppendLine("            ");
        sb.AppendLine("            // 添加当前活动状态");
        sb.AppendLine("            this.classList.add('active');");
        sb.AppendLine("            ");
        sb.AppendLine("            const filter = this.getAttribute('data-filter');");
        sb.AppendLine("            ");
        sb.AppendLine("            // 过滤结果");
        sb.AppendLine("            resultRows.forEach(row => {");
        sb.AppendLine("                if (filter === 'all' || row.getAttribute('data-status') === filter) {");
        sb.AppendLine("                    row.classList.remove('hidden');");
        sb.AppendLine("                } else {");
        sb.AppendLine("                    row.classList.add('hidden');");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("        });");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 初始化模态框");
        sb.AppendLine("function initializeModals() {");
        sb.AppendLine("    const screenshotModal = document.getElementById('screenshotModal');");
        sb.AppendLine("    const testDetailsModal = document.getElementById('testDetailsModal');");
        sb.AppendLine("    ");
        sb.AppendLine("    // 关闭按钮事件");
        sb.AppendLine("    document.querySelectorAll('.close').forEach(closeBtn => {");
        sb.AppendLine("        closeBtn.addEventListener('click', function() {");
        sb.AppendLine("            screenshotModal.style.display = 'none';");
        sb.AppendLine("            testDetailsModal.style.display = 'none';");
        sb.AppendLine("        });");
        sb.AppendLine("    });");
        sb.AppendLine("    ");
        sb.AppendLine("    // 点击模态框外部关闭");
        sb.AppendLine("    window.addEventListener('click', function(e) {");
        sb.AppendLine("        if (e.target === screenshotModal) {");
        sb.AppendLine("            screenshotModal.style.display = 'none';");
        sb.AppendLine("        }");
        sb.AppendLine("        if (e.target === testDetailsModal) {");
        sb.AppendLine("            testDetailsModal.style.display = 'none';");
        sb.AppendLine("        }");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 初始化滚动监听");
        sb.AppendLine("function initializeScrollSpy() {");
        sb.AppendLine("    const sections = document.querySelectorAll('.report-section');");
        sb.AppendLine("    const navLinks = document.querySelectorAll('.nav-link');");
        sb.AppendLine("    ");
        sb.AppendLine("    window.addEventListener('scroll', function() {");
        sb.AppendLine("        let current = '';");
        sb.AppendLine("        ");
        sb.AppendLine("        sections.forEach(section => {");
        sb.AppendLine("            const sectionTop = section.offsetTop - 100;");
        sb.AppendLine("            const sectionHeight = section.clientHeight;");
        sb.AppendLine("            ");
        sb.AppendLine("            if (window.pageYOffset >= sectionTop && ");
        sb.AppendLine("                window.pageYOffset < sectionTop + sectionHeight) {");
        sb.AppendLine("                current = section.getAttribute('id');");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("        ");
        sb.AppendLine("        navLinks.forEach(link => {");
        sb.AppendLine("            link.classList.remove('active');");
        sb.AppendLine("            if (link.getAttribute('href') === '#' + current) {");
        sb.AppendLine("                link.classList.add('active');");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 打开截图模态框");
        sb.AppendLine("function openScreenshot(imageSrc) {");
        sb.AppendLine("    const modal = document.getElementById('screenshotModal');");
        sb.AppendLine("    const modalImage = document.getElementById('modalImage');");
        sb.AppendLine("    ");
        sb.AppendLine("    modalImage.src = imageSrc;");
        sb.AppendLine("    modal.style.display = 'block';");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 显示测试详情");
        sb.AppendLine("function showTestDetails(testName) {");
        sb.AppendLine("    const modal = document.getElementById('testDetailsModal');");
        sb.AppendLine("    const content = document.getElementById('testDetailsContent');");
        sb.AppendLine("    ");
        sb.AppendLine("    if (typeof testDetailsData !== 'undefined' && testDetailsData[testName]) {");
        sb.AppendLine("        const details = testDetailsData[testName];");
        sb.AppendLine("        content.innerHTML = formatTestDetails(details);");
        sb.AppendLine("    } else {");
        sb.AppendLine("        content.innerHTML = '<h2>测试详情: ' + testName + '</h2><p>详细信息不可用</p>';");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    modal.style.display = 'block';");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 格式化测试详情");
        sb.AppendLine("function formatTestDetails(details) {");
        sb.AppendLine("    let html = '<h2>' + details.testName + '</h2>';");
        sb.AppendLine("    html += '<div class=\"test-detail-grid\">';");
        sb.AppendLine("    html += '<div><strong>状态:</strong> ' + details.status + '</div>';");
        sb.AppendLine("    html += '<div><strong>开始时间:</strong> ' + details.startTime + '</div>';");
        sb.AppendLine("    html += '<div><strong>结束时间:</strong> ' + details.endTime + '</div>';");
        sb.AppendLine("    html += '<div><strong>执行时间:</strong> ' + details.duration + '</div>';");
        sb.AppendLine("    html += '</div>';");
        sb.AppendLine("    ");
        sb.AppendLine("    if (details.errorMessage) {");
        sb.AppendLine("        html += '<h3>错误信息</h3>';");
        sb.AppendLine("        html += '<pre>' + details.errorMessage + '</pre>';");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    if (details.stackTrace) {");
        sb.AppendLine("        html += '<h3>堆栈跟踪</h3>';");
        sb.AppendLine("        html += '<pre>' + details.stackTrace + '</pre>';");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    return html;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// 格式化JSON数据");
        sb.AppendLine("function formatJson(obj) {");
        sb.AppendLine("    return JSON.stringify(obj, null, 2);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Chart.js 配置");
        sb.AppendLine("if (typeof Chart !== 'undefined') {");
        sb.AppendLine("    Chart.defaults.font.family = 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif';");
        sb.AppendLine("    Chart.defaults.color = '#2c3e50';");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}